<a href="https://colab.research.google.com/github/Haneen-Alahmadi/Data_Preprocessing/blob/main/dataPreprocessing1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot

In [2]:
data = pd.read_csv('/content/HTNDataset.csv')

In [3]:
data

Country   Age  Cholesterol  HTN
0     USA  55.0        300.0  Yes
1   Egypt  30.0        200.0   No
2  France  45.0        150.0   No
3     USA  20.0        250.0  Yes
4   Egypt  39.0          NaN   No
5   Egypt  58.0        290.0  Yes
6   Egypt   NaN        190.0   No
7   Egypt  29.0        170.0   No
8  France  60.0        240.0  Yes
9     USA  65.0        350.0  Yes

X Independent variables

In [4]:
X = data.iloc[: , :-1].values

In [5]:
X

array([['USA', 55.0, 300.0],
       ['Egypt', 30.0, 200.0],
       ['France', 45.0, 150.0],
       ['USA', 20.0, 250.0],
       ['Egypt', 39.0, nan],
       ['Egypt', 58.0, 290.0],
       ['Egypt', nan, 190.0],
       ['Egypt', 29.0, 170.0],
       ['France', 60.0, 240.0],
       ['USA', 65.0, 350.0]], dtype=object)

-1 -> Y dependent variables

In [6]:
Y = data.iloc[: , -1].values

In [7]:
Y

array(['Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes'],
      dtype=object)

**Missing Data**

In [8]:
from sklearn.impute import SimpleImputer

In [9]:
imputer = SimpleImputer(missing_values= np.nan, strategy='mean')

In [10]:
imputer.fit(X[:,1:3])

SimpleImputer()

In [11]:
X[:,1:3]= imputer.transform(X[:,1:3])

In [12]:
X

array([['USA', 55.0, 300.0],
       ['Egypt', 30.0, 200.0],
       ['France', 45.0, 150.0],
       ['USA', 20.0, 250.0],
       ['Egypt', 39.0, 237.77777777777777],
       ['Egypt', 58.0, 290.0],
       ['Egypt', 44.55555555555556, 190.0],
       ['Egypt', 29.0, 170.0],
       ['France', 60.0, 240.0],
       ['USA', 65.0, 350.0]], dtype=object)

**Encoding Categorical Data**

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [18]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0] )], remainder= 'passthrough')

In [19]:
X = np.array(ct.fit_transform(X))

In [20]:
X

array([[0.0, 0.0, 1.0, 55.0, 300.0],
       [1.0, 0.0, 0.0, 30.0, 200.0],
       [0.0, 1.0, 0.0, 45.0, 150.0],
       [0.0, 0.0, 1.0, 20.0, 250.0],
       [1.0, 0.0, 0.0, 39.0, 237.77777777777777],
       [1.0, 0.0, 0.0, 58.0, 290.0],
       [1.0, 0.0, 0.0, 44.55555555555556, 190.0],
       [1.0, 0.0, 0.0, 29.0, 170.0],
       [0.0, 1.0, 0.0, 60.0, 240.0],
       [0.0, 0.0, 1.0, 65.0, 350.0]], dtype=object)

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
Y = LabelEncoder().fit_transform(Y)

In [23]:
Y

array([1, 0, 0, 1, 0, 1, 0, 0, 1, 1])

**Splitting the dataset**

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, Y_train, Y_test= train_test_split(X,Y,test_size= 0.2, random_state=1)

train= 80%
test = 20%

**Feature Scaling**

In [28]:
from sklearn.preprocessing import StandardScaler

In [30]:
sc = StandardScaler()

In [31]:
X_train[ :, 3: ]= sc.fit_transform(X_train[ :, 3: ])

In [32]:
X_train

array([[1.0, 0.0, 0.0, 0.18689534890991308, -1.0334323227896105],
       [1.0, 0.0, 0.0, -0.2107543296218165, 0.07060717733345134],
       [0.0, 0.0, 1.0, 0.9344767445495644, 1.5084260612146485],
       [0.0, 0.0, 1.0, -1.5707162302003312, 0.35303588666725805],
       [1.0, 0.0, 0.0, -0.8549468088432183, -0.8023542878801324],
       [1.0, 0.0, 0.0, -0.9265237509789296, -1.4955883926085667],
       [0.0, 1.0, 0.0, 1.2923614552281208, 0.12195785175777996],
       [1.0, 0.0, 0.0, 1.1492075709566982, 1.2773480263051704]],
      dtype=object)

In [33]:
X_test[ :, 3: ]= sc.transform(X_test[ :, 3: ])

In [34]:
X_test

array([[0.0, 1.0, 0.0, 0.21870732319245131, -1.9577444624275229],
       [0.0, 0.0, 1.0, 1.6502461659066774, 2.663816235762039]],
      dtype=object)